### ISSUE TITLE
Anatomical embedding for 2D and 3D medical data

### ISSUE THREAD

**Issue by nifla2000** [alibaba-damo-academy/self-supervised-anatomical-embedding-v2#3]
Thanks for this interesting work!
I'm in a specific task where I need to obtain matching landmarks between an Ultrasound sweep/frame and a paired CT volume. Would you think this repository can be useful in my problem as you did it only for 3D data? Appreciate your response.

**Comment by viggin** [comment]
I am not familiar with CT-US matching. If you ask for my suggestion, I think you may refer to the cross-modality matching pipeline in our paper. For example, you can first generate some simulated US images from CT (https://campar.in.tum.de/pub/wein2008ctusfusion/wein2008ctusfusion.pdf) and use the generated CT-US pairs to train an initial CrossSAM model. Then, you may need some non-rigid registration finetuning using specialized similarity metrics and auxiliary organ masks (https://aapm.onlinelibrary.wiley.com/doi/abs/10.1002/mp.16396).
