### ISSUE TITLE
Obtaining matching for 2D data

### ISSUE THREAD

**Issue by nifla2000** [alibaba-damo-academy/self-supervised-anatomical-embedding-v2#5]
As in your paper, do you have a model and (or) checkpoints for 2D data? (X-ray)

**Comment by aa1234241** [comment]
Hi, this repo only contains code for 3D volume data. SAM for intra-modality matching, UAE-S for better intra-modality matching and UAE-M for inter-modality matching like CT-MRI pair.

**Comment by nifla2000** [comment]
can you share your code or even checkpoints?

**Comment by aa1234241** [comment]
I didn't implement the 2D version. You can try to  replace the 3D backbone.

**Comment by viggin** [comment]
Yes, we didn't include 2D code and models here. It should be easy to adapt the code and train a 2D model.

**Comment by nifla2000** [comment]
> Yes, we didn't include 2D code and models here. It should be easy to adapt the code and train a 2D model.

I found it difficult to specify (or change) the pipelines, views, and other pre-processings for 2D data. If you have any of your past codes, can you please share them? 
(if you do not want to put it in this repo please email me. niflanasvi2000@gmail.com) 
Thank you

**Comment by aa1234241** [comment]
> > Yes, we didn't include 2D code and models here. It should be easy to adapt the code and train a 2D model.
> 
> I found it difficult to specify (or change) the pipelines, views, and other pre-processings for 2D data. If you have any of your past codes, can you please share them? (if you do not want to put it in this repo please email me. [niflanasvi2000@gmail.com](mailto:niflanasvi2000@gmail.com)) Thank you

Hello, sorry I only re-implemented the 3D SAM code. The original code, which included both 2D and 3D models, is not available due to company policy.
