### ISSUE TITLE
dataset.cumulative_sizes 

### ISSUE THREAD

**Issue by nifla2000** [alibaba-damo-academy/self-supervised-anatomical-embedding-v2#6]
The defined class Dataset3dsam(object) has no attribute called "cumulative_sizes'. But in class InfiniteBalancedBatchSampler(Sampler) in lines 56 and 57, dataset.cumulative_sizes attribute it used, which gives an attribute error.

**Comment by aa1234241** [comment]
Hello, which model are you training? For the original SAM model,  comment sam/datasets/builder.py lines 144 and 145.
<img width="786" alt="Screen Shot 2024-02-18 at 9 48 04 PM" src="https://github.com/alibaba-damo-academy/self-supervised-anatomical-embedding-v2/assets/24704252/b1835013-a2e5-48aa-8d30-207b32996252"> and uncomment the following lines.
<img width="882" alt="Screen Shot 2024-02-18 at 9 49 33 PM" src="https://github.com/alibaba-damo-academy/self-supervised-anatomical-embedding-v2/assets/24704252/bd3df8c2-91f6-4f84-87c1-d325196048c6">

**Comment by nifla2000** [comment]
I was using the original SAM module. Thank you for clarifying.
