### ISSUE TITLE
Masks and Labels in SAME registration

### ISSUE THREAD

**Issue by MohammedSB** [alibaba-damo-academy/self-supervised-anatomical-embedding-v2#9]
Hi,

We have opened these issues in the SAME repo, but still have not gotten a response, so we thought maybe we can try here. In SAME, it asks for the dataset class to be structures as follows:
```
root/
|-- case1/
|   |-- case1_image.nii.gz
|   |-- case1_label.nii.gz
|   |-- case1_mask.nii.gz
|-- case2/
```
with a `_label` and a `_mask` files. Is there a script in this repo that we can use for generating those?
Is it this file: `misc/merge_mask_label_multi_process.py`?

Also, from my understanding, the `_label` file is organ masks while `_mask` is just background vs. body mask, is my understanding correct?

**Comment by aa1234241** [comment]
Hi, this repository is for the UAE project and the re-implementation of SAM. The script misc/merge_mask_label_multi_process.py is used for data processing in this project. I think you are right, the mask is just the body mask and the label is the detailed organ masks.
